language: python
python:
  - 2.7
  - 3.6
  - nightly
install:
  - pip install nose pytz
script:
  - nosetests --with-doctest test/ unstdlib/standard/
email:
    on_success: change
    on_failure: change
